---
- name: Ubuntu 20.04 Enable UFW
  community.general.ufw:
    state: enabled
    default: deny

- name: Enable logging UFW
  community.general.ufw:
    logging: 'on'

# SSH
- name: UFW allow SSH Port
  community.general.ufw:
    rule: allow
    name: OpenSSH

# HTTP
- name: UFW allow HTTP 80
  community.general.ufw:
    rule: allow
    port: '80'

- name: UFW allow HTTPS 443
  community.general.ufw:
    rule: allow
    port: '443'

# qbittorrent
- name: UFW allow HTTP 6881
  community.general.ufw:
    rule: allow
    port: '6881'

- name: UFW allow HTTP 6881 UDP
  community.general.ufw:
    rule: allow
    port: '6881'
    proto: udp

- name: UFW allow HTTP 8081
  community.general.ufw:
    rule: allow
    port: '8081'

# portainer
- name: UFW allow HTTP 8080
  community.general.ufw:
    rule: allow
    port: '8080'

# DNS
- name: UFW allow DNS 53
  community.general.ufw:
    rule: allow
    port: '53'

- name: UFW allow DNS 53\udp
  community.general.ufw:
    rule: allow
    port: '53'
    proto: udp

- name: UFW allow Postgres 5432
  community.general.ufw:
    rule: allow
    port: '5432'
