---
# tasks file for roles/default-packages

- name: Install packages ubuntu 20.04
  ansible.builtin.apt:
    name:
      - fish
      - mc
      - git
      - htop
      - tmux
      - vim
      - iotop
    state: present
    update_cache: true
    cache_valid_time: 86400
  become: true
  when: ansible_facts['os_family'] == 'Debian'
