---
# tasks file for roles/dnsmasq
- name: Install dnsmasq
  ansible.builtin.apt:
    name: dnsmasq
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: Disable and Stop systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: no
    state: stopped

- name: Copy dnsmasq config file
  ansible.builtin.copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - Restart dnsmasq service

- name: Enable dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    enabled: yes
    state: started

